name: Node.js Tags

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: |
        npm install -g @angular/cli@19.2.8 && npm ci
        ng build --aot --configuration production --base-href=./index.html
        find dist/notebook-privapps/browser
