name: Node.js dev

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g @angular/cli@16.2.12 && npm ci --legacy-peer-deps

    - run: ng build --aot --build-optimizer --configuration production --base-href=/index.html
    - uses: actions/checkout@v2
      with:
        ref: test
        path: doc
    - name: update repo for github pages
      shell: bash
      run: |
        cd doc/docs
        mv assets/config.json /tmp/$$
        mv data /tmp/
        rm -fr *
        cp -R ../../dist/notebook-privapps/* .
        mv /tmp/$$ assets/config.json
        cd ..
        rm -f notebook-web.tar.xz
        tar cJf notebook-web.tar.xz docs
        mv /tmp/data docs/
        git add -A .
        git config --local user.email "privapps"
        git config --local user.name "privapps"
        git commit -m "sync with code $(date +'%F')" && \
        git push "https://${GITHUB_ACTOR}:${{ github.token }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:test || echo
